### ISSUE TITLE
Missing play generators in 0.7.0

### ISSUE THREAD

**Issue by ploddi** [playframework/play-grpc#124]
I could not find where `play-generators` package is published after its extraction from `akka-grpc` sbt plugin.

**Comment by renatocaval** [comment]
The generators where moved on this PR: https://github.com/playframework/play-grpc/pull/101. Merged on 8th June. 

The 0.7.0 release was done on the 18th April. So it's normal that the artefacts were not published for 0.7.0.

**Comment by hansidm** [comment]
I see that 0.7.1 has been released and still the `play-generators` are missing from `akka-grpc` sbt plugin.. Any updates on that?

**Comment by raboof** [comment]
The `play-generators` used to be part of `akka-grpc`, but have now been factored out and moved to `play-grpc` so they can evolve on their own more easily.

Until we release a new version of `play-grpc` with the moved generators, you can use Akka gRPC 0.6.2 with play-grpc.

**Comment by renatocaval** [comment]
@ploddi, we are about to release Lagom 1.5.2. We will cut a release of play-grpc as next.

**Comment by renatocaval** [comment]
@ploddi, we released Lagom 1.5.3 and I just triggered the release of Play gRPC 0.7.1. 

It's on its way! I'm closing this issue, therefore.
