### ISSUE TITLE
Play generators not published to sbt-plugin repos

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-grpc#159]
In #158, we discover that the play generators plugin is being published to https://dl.bintray.com/playframework/maven/com/lightbend/play/ while the correct location should be https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.play/.

As of today, users need to add extra resolver to find the plugin.

**Comment by ignasi35** [comment]
I think this is no longer valid.
