### ISSUE TITLE
Play gRPC not working with Play 2.8 due to incompatible binary

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-grpc#190]
Play gRPC is not working with Play 2.8, because it's using a field from `ServiceEndpoint` that were renamed in Play 2.8 (see [diff](https://github.com/playframework/playframework/commit/880be94d78ac9ed9e121c82004d208299d8586d0#diff-1b30b2fb173639590b59648f597ef39aR19-R28)). `ServiceEndpoint` is marked as `@ApiMayChange`.

We don't want to move `play-grpc` to Play 2.8 because:

1. it will be broken for Play 2.7 users
2. it will pull Akka v2.6.x, while `akka-grpc` is on v2.5.x. This is a strategical choice and we want to keep it on v2.5.x.

Actually, in both cases, we want to keep it compatible with the previous Play and Akka versions (v2.7.x and v2.5.x). There is impact for Lagom 1.5.x as well.

I see the following options: 

1. Backport the new fields to 2.7.x while keeping the old ones as deprecated. Release a new `play-grpc` version that uses the new field. That will make the next version compatible with Play 2.8.x and will allow the previous version to still work with any Play 2.7.x version. An old `play-grpc` binary won't work with Play 2.8, but that's fine, IMO. People will need to update it. 
2. Re-add the fields in 2.8, but as deprecated. This has the advantage of keeping previous `play-grpc` compatible with Play 2.8.1 and forward, but we are only postponing the solution. We want to stop using deprecated fields.

**Comment by raboof** [comment]
> it will pull Akka v2.6.x, while `akka-grpc` is on v2.5.x. This is a strategical choice and we want to keep it on `v2.5.x`.

To clarify: `akka-grpc` is of course intended to work with Akka 2.6 just fine - but indeed we haven't taken the plunge to require Akka 2.6 for akka-grpc users just yet.

This is of course entirely up to you, but moving Play gRPC master to Play 2.8 (and only backporting essential bugfixes to the branch supporting 2.7 on customer request) seems worth considering.

**Comment by renatocaval** [comment]
We will just move to Play 2.8 and Akka 2.6. Next release will be 0.8.0 and is intended to be use starting from Play 2.8.

**Comment by raboof** [comment]
Sounds reasonable to me! For reference, I've started issues about requiring Akka 2.6 (https://github.com/akka/akka-grpc/issues/762) and binary compatibility (https://github.com/akka/akka-grpc/issues/761) in Akka gRPC.

**Comment by raboof** [comment]
done in #195
