### ISSUE TITLE
ActorMaterializer in package stream is deprecated since 2.6.0

### ISSUE THREAD

**Issue by akkie** [playframework/play-grpc#221]
With 0.8.1 and Play 2.8, I get the following message:

```
class ActorMaterializer in package stream is deprecated (since 2.6.0): The Materializer now has all methods the ActorMaterializer used to have
[error]   private val clientState = new ClientState(settings, akka.event.Logging(mat.asInstanceOf[ActorMaterializer].system, this.getClass))
```

**Comment by raboof** [comment]
Thanks for the report! This is indeed inelegant, and something that we hope to fix. It is actually a problem in the upstream akka-grpc project that play-grpc builds upon, and stems from the fact that akka-grpc also still supports Akka 2.5, so it cannot 'simply' use the new Materializer API's.

That said, Akka 2.5.30 (which is expected in a week or so) introduces some API's that will make it easier to gracefully support Akka 2.5 and 2.6 side-by-side, and we can use those in akka-grpc to avoid directly referencing ActorMaterializer. There is some work-in-progress in that area in https://github.com/akka/akka-grpc/pull/824

Until that time, however, you will see this warning. This is problematic when you want to enable 'fatal warnings', of course. In that case I would recommend configuring the scala 'silencer' compiler plugin to suppress those warnings (see for example https://github.com/ghik/silencer/#global-regex-based-suppression and https://github.com/ghik/silencer/#filename-based-suppression).

**Comment by Tochemey** [comment]
@akkie  You can add this to your project for the meantime:
```
scalacOptions ++= Seq(
      "-Xfatal-warnings",
      "-deprecation",
      "-Xlint",
      "-P:silencer:globalFilters=Unused import;deprecated"
    )
```
using the silencer

**Comment by ignasi35** [comment]
I think #264 fixes this.
