### ISSUE TITLE
Expectation of a new release

### ISSUE THREAD

**Issue by Tochemey** [playframework/play-grpc#229]
Hello I would like to know whether we can expect a release of play-grpc sequel to this issue https://github.com/playframework/play-grpc/pull/228 has been addressed and play-grpc is up to date with the new akka-grpc.

**Comment by raboof** [comment]
I'll make one after Akka gRPC 0.8.2 has made it to maven central and play-grpc has been updated to that :+1:

**Comment by raboof** [comment]
Don't frown, that happened pretty fast #230 :)

**Comment by Tochemey** [comment]
Hello @raboof I cannot see it yet on maven

**Comment by raboof** [comment]
@Tochemey sorry, that PR is not yet the play-grpc release, it's the upgrade to Akka gRPC 0.8.2 which was a prerequisite. This means I can now start on the play-grpc release. I started on it, but it appears there is a problem with the travis configuration (https://travis-ci.com/github/playframework/play-grpc/requests), so we'll have to look into that. I'm trying #233 but I'm not sure that's it. If you can spot the problem then your help would be much appreciated!

**Comment by Tochemey** [comment]
Hey it seems your PR is good

**Comment by Tochemey** [comment]
@raboof Please any update on the release?

**Comment by raboof** [comment]
As you can see in https://travis-ci.com/github/playframework/play-grpc/requests travis is still not picking up the publish task for the tag. If you can help figure out what's wrong there that would be much appreciated, since I'm quite busy on the Akka gRPC side right now.

**Comment by Tochemey** [comment]
@raboof I am too with travis and sbt but per the doc https://github.com/dwijnand/sbt-travisci don't you think we need to add this line in the travis.yml file
```
scala:
  - 2.12.8
  - 2.13.1
```

**Comment by raboof** [comment]
Getting closer: publishing is now triggered correctly, but we identified a problem upstream so we want to cut an Akka gRPC 0.8.4 and update play-grpc to that today, before releasing play-grpc.

**Comment by Tochemey** [comment]
@raboof Thanks for the update. I am currently using akka 2.6.3. I would like to know when that release is out  whether I have to change my akka version or I can still use the version I have at the moment.

**Comment by raboof** [comment]
> I am currently using akka 2.6.3. I would like to know when that release is out whether I have to change my akka version or I can still use the version I have at the moment.

I think that should work fine (though I'd recommend upgrading to 2.6.4 anyway of course ;) )

**Comment by raboof** [comment]
0.8.2 should be on maven central now!

**Comment by Tochemey** [comment]
Yeah thanks. I am using it already
