### ISSUE TITLE
Generated Java code uses Materializer

### ISSUE THREAD

**Issue by ennru** [playframework/play-grpc#298]
In contrast to the Scala DSL, the Java DSL still requires the explict use of a materializer.

That should be aligned.

https://github.com/playframework/play-grpc/blob/0f0ff7239ade48f7c385c2acddfd49ba57294ef0/play-interop-test-java/src/main/java/controllers/GreeterServiceImpl.java#L23

https://github.com/playframework/play-grpc/blob/0f0ff7239ade48f7c385c2acddfd49ba57294ef0/play-interop-test-scala/src/main/scala/controllers/GreeterServiceImpl.scala#L20

**Comment by ignasi35** [comment]
Fixed in #318
