### ISSUE TITLE
Doesn't support multiple services in same package

### ISSUE THREAD

**Issue by ctoomey** [playframework/play-grpc#348]
When I had 2 services defined in a single package, the code generator failed with the error `pregistry/AbstractRouter.scala: Tried to write the same file twice.`.

Looked back at the generator source code and found this is due to a simple bug at this line: https://github.com/playframework/play-grpc/blob/master/play-generators/src/main/scala/play/grpc/gen/scaladsl/PlayScalaServerCodeGenerator.scala#L27 .

Instead of
```
b.setName(s"${service.packageDir}/AbstractRouter.scala")
```

it should be
```
b.setName(s"${service.packageDir}/Abstract${service.name}Router.scala")
```

similar to https://github.com/playframework/play-grpc/blob/master/play-generators/src/main/scala/play/grpc/gen/scaladsl/PlayScalaServerCodeGenerator.scala#L40 .

**Comment by ignasi35** [comment]
Nice find (and a simple fix too). Would you like to PR the improvement?

**Comment by ctoomey** [comment]
Yes I will when I have time.

**Comment by ctoomey** [comment]
Thanks for fixing @mkurz and @tsawada .

**Comment by mkurz** [comment]
@ctoomey You need this for Play 2.8? Or are you upgrading to 2.9 or 3.0 anyway?

**Comment by ctoomey** [comment]
> @ctoomey You need this for Play 2.8? Or are you upgrading to 2.9 or 3.0 anyway?

I've left the company where we'd been using this and we'd somehow avoided needing this in any case for what we were doing. So I don't have a specific need for it any more.
