### ISSUE TITLE
Transfer issues from akka-grpc

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-grpc#35]
There's a bunch of play-related issues in [`akka-grpc`](https://github.com/akka/akka-grpc/search?p=2&q=play&type=Issues) we should transfer here.

Unfortunately the repos belong to different organizations to GitHub's `transfer issue (beta)` doesn't seem to work.

**Comment by dwijnand** [comment]
I had a look at the https://github.com/akka/akka-grpc/labels/play label, and they all look like issues related to the Play integration that lives in akka-grpc.

**Comment by ignasi35** [comment]
@dwijnand are you referring to the 2 codegen templates in https://github.com/akka/akka-grpc/tree/master/codegen/src/main/twirl/templates ?

**Comment by raboof** [comment]
@ignasi35 yes, we plan to do that (https://github.com/akka/akka-grpc/issues/517) but there are some PR's in the work for this, so might be smart to postpone that until those are finalized.

**Comment by dwijnand** [comment]
@ignasi35 yeah those, and I agree the issues should move with the code.

**Comment by ignasi35** [comment]
This is complete
