### ISSUE TITLE
Please consider to release a new version of main branch

### ISSUE THREAD

**Issue by zhengcan** [playframework/play-grpc#402]
The code of main branch supports latest akka-grpc already. But the latest v0.9.1 of play-grpc doesn't support yet.
Please release a new version of this project to allow us migrate to latest codebase.
Thanks

**Comment by mkurz** [comment]
I try to upgrade to the last versions before (see #395) and if that works we can release a RC.

**Comment by zhengcan** [comment]
I'm waiting for it 🍡

**Comment by ihostage** [comment]
@mkurz WDYT about `groupID` of the next release?
The latest release was published in [`com.lightbend.play`](https://repo1.maven.org/maven2/com/lightbend/play/)
Then you changed to `com.typesafe.play` in #420 and told Steward (https://github.com/scala-steward-org/scala-steward/pull/2606) about this but no one release haven't been published.
Of course, for Play 3 we will change groupId to `org.playframework`.

The question is next. Should we release for Play 2.9 with `com.typesafe.play` or change to `org.playframework` right now?

I'm ok with both cases, but using `com.typesafe.play` for Play 2.9 is liked my more.

**Comment by mkurz** [comment]
Let's stay with `com.typesafe.play` for 2.9 and `org...` for 3, like always.

**Comment by ihostage** [comment]
@mkurz Is next version should be `0.9.2` or `0.10.0` because we changed a groupId? 
I think it should be `0.10.0`.

**Comment by mkurz** [comment]
Yes 0.10.0 makes most sense.

**Comment by ihostage** [comment]
`0.10.0` released!  🎉 

https://github.com/playframework/play-grpc/releases/tag/0.10.0
