### ISSUE TITLE
Drop Lagom modules

### ISSUE THREAD

**Issue by ihostage** [playframework/play-grpc#471]
Lagom is deprecated and approaching EOL (July 1, 2024). I think we shouldn't support these modules and remove all of them.

**Comment by ihostage** [comment]
@mkurz WDYT?

**Comment by mkurz** [comment]
Yes I think so, I think this is what is blocking play-grpc to move on (?)

**Comment by sentenza** [comment]
@mkurz @ihostage Could you please review #477 ?

**Comment by sentenza** [comment]
@ihostage could you please review #477 so I will able to keep updating this library? The current version of play-grpc is blocking my company right now, because our legacy services are using Scala Play and gRPC and we need to upgrade them to Play 3.0.0.

**Comment by mkurz** [comment]
@sentenza I have time tomorrow to review, maybe Sergey has time today, if not please be patient, thanks!
