### ISSUE TITLE
Migrate docs to Antora

### ISSUE THREAD

**Issue by ihostage** [playframework/play-grpc#472]
The doc for this Play module was published on https://developer.lightbend.com/docs/play-grpc/current/
But now this doc is unavailable. 

I think we can use Play SOAP experience (https://playframework.github.io/play-soap/2.x/) and do something similar for this.

**Comment by ihostage** [comment]
@mkurz WDYT?

**Comment by mkurz** [comment]
Yes :+1:

**Comment by ihostage** [comment]
Docs published https://playframework.github.io/play-grpc/0.9.x/index.html
