### ISSUE TITLE
Why use pekko-sbt-paradox plugin?

### ISSUE THREAD

**Issue by pjfanning** [playframework/play-grpc#507]
https://github.com/playframework/play-grpc/blob/17b5fa50252a254b8e267a471de85b4341c34bcd/project/plugins.sbt#L2

This SBT plugin is for generating Pekko docs for the Apache Pekko website. Why does this project need it?

**Comment by ihostage** [comment]
Hi, @pjfanning! 
It doesn't needed 😉 
Just Matthias changed all Akka things to Pekko in #490 including this plugin.
But in real we don't use it now and will remove.
Thank you for your note 👍

**Comment by mkurz** [comment]
Removed in
- #509
